model_name_or_path: models/Qwen2.5-1.5B-Instruct
trust_remote_code: true

stage: sft
do_train: true
finetuning_type: full

dataset: nrc_sorbian_mt
dataset_dir: data/nrc/sft
template: qwen
cutoff_len: 1024
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

output_dir: runs/nrc_qwen25_15b
logging_steps: 10
save_steps: 500
save_total_limit: 3
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: none

per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 7.0e-5
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_steps: 0
weight_decay: 0.0
max_grad_norm: 1.0
optim: adamw_torch
bf16: true
ddp_timeout: 180000000
seed: 42
